CREATE TABLE Cliente (id INT NOT NULL AUTO_INCREMENT,
Razão_Social VARCHAR(60),
CNPJ VARCHAR(18),
Email VARCHAR(60),
Telefone VARCHAR(11),
Logradouro VARCHAR(70),
Cidade VARCHAR(20),
CEP VARCHAR(10),
Estado VARCHAR(2),
PRIMARY KEY (id)
);