CREATE TABLE Usuario (id INT NOT NULL AUTO_INCREMENT,
Nome VARCHAR(60),
Nascimento VARCHAR(10),
Telefone VARCHAR(11),
Email VARCHAR(60),
CPF INT(11),
Login VARCHAR(12),
Senha VARCHAR(12),
PRIMARY KEY (id)
);


